/*
 * KERNEL BYPASS FRAMEWORK
 * IOCTL Codes for Driver Communication
 */

#pragma once

#ifdef _KERNEL_MODE
    #include <ntddk.h>
#else
    #include <winioctl.h>
#endif

// ============================================
// VMCALL Numbers (for hypervisor communication)
// ============================================

#define VMCALL_TEST             0x1
#define VMCALL_READ_MEMORY      0x2
#define VMCALL_WRITE_MEMORY     0x3
#define VMCALL_GET_CR3          0x4
#define VMCALL_EPT_HOOK         0x5
#define VMCALL_EPT_UNHOOK       0x6
#define VMCALL_SPOOF_CPUID      0x7
#define VMCALL_HIDE_PAGE        0x8

// ============================================
// Device Type
// ============================================

#define KB_DEVICE_TYPE          0x8000  // Custom device type

// ============================================
// IOCTL Function Codes
// ============================================

// Memory Operations (0x800 - 0x8FF)
#define IOCTL_KB_READ_MEMORY        CTL_CODE(KB_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_WRITE_MEMORY       CTL_CODE(KB_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_ALLOC_MEMORY       CTL_CODE(KB_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_FREE_MEMORY        CTL_CODE(KB_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_PROTECT_MEMORY     CTL_CODE(KB_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_QUERY_MEMORY       CTL_CODE(KB_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Process Operations (0x900 - 0x9FF)
#define IOCTL_KB_GET_PROCESS        CTL_CODE(KB_DEVICE_TYPE, 0x900, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_GET_PROCESS_BASE   CTL_CODE(KB_DEVICE_TYPE, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_GET_MODULE         CTL_CODE(KB_DEVICE_TYPE, 0x902, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_ENUM_MODULES       CTL_CODE(KB_DEVICE_TYPE, 0x903, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_HIDE_PROCESS       CTL_CODE(KB_DEVICE_TYPE, 0x904, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_PROTECT_PROCESS    CTL_CODE(KB_DEVICE_TYPE, 0x905, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_ELEVATE_HANDLE     CTL_CODE(KB_DEVICE_TYPE, 0x906, METHOD_BUFFERED, FILE_ANY_ACCESS)

// HWID Operations (0xA00 - 0xAFF)
#define IOCTL_KB_SPOOF_HWID         CTL_CODE(KB_DEVICE_TYPE, 0xA00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_GET_HWID           CTL_CODE(KB_DEVICE_TYPE, 0xA01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_RESTORE_HWID       CTL_CODE(KB_DEVICE_TYPE, 0xA02, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_RANDOMIZE_HWID     CTL_CODE(KB_DEVICE_TYPE, 0xA03, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Callback Operations (0xB00 - 0xBFF)
#define IOCTL_KB_ENUM_CALLBACKS     CTL_CODE(KB_DEVICE_TYPE, 0xB00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_REMOVE_CALLBACK    CTL_CODE(KB_DEVICE_TYPE, 0xB01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_RESTORE_CALLBACK   CTL_CODE(KB_DEVICE_TYPE, 0xB02, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_DISABLE_ALL        CTL_CODE(KB_DEVICE_TYPE, 0xB03, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Driver Operations (0xC00 - 0xCFF)
#define IOCTL_KB_HIDE_DRIVER        CTL_CODE(KB_DEVICE_TYPE, 0xC00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_UNLOAD_DRIVER      CTL_CODE(KB_DEVICE_TYPE, 0xC01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_DRIVER_STATUS      CTL_CODE(KB_DEVICE_TYPE, 0xC02, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Hypervisor Operations (0xD00 - 0xDFF)
#define IOCTL_KB_HYPER_INIT         CTL_CODE(KB_DEVICE_TYPE, 0xD00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_HYPER_STOP         CTL_CODE(KB_DEVICE_TYPE, 0xD01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_HYPER_STATUS       CTL_CODE(KB_DEVICE_TYPE, 0xD02, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_EPT_HOOK           CTL_CODE(KB_DEVICE_TYPE, 0xD03, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_EPT_UNHOOK         CTL_CODE(KB_DEVICE_TYPE, 0xD04, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_VMCALL             CTL_CODE(KB_DEVICE_TYPE, 0xD05, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Firmware Operations (0xE00 - 0xEFF)
#define IOCTL_KB_FIRMWARE_INFO      CTL_CODE(KB_DEVICE_TYPE, 0xE00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_SMM_CALL           CTL_CODE(KB_DEVICE_TYPE, 0xE01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_UEFI_VARIABLE      CTL_CODE(KB_DEVICE_TYPE, 0xE02, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Utility Operations (0xF00 - 0xFFF)
#define IOCTL_KB_GET_VERSION        CTL_CODE(KB_DEVICE_TYPE, 0xF00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_PING               CTL_CODE(KB_DEVICE_TYPE, 0xF01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_GET_KERNEL_BASE    CTL_CODE(KB_DEVICE_TYPE, 0xF02, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KB_PATTERN_SCAN       CTL_CODE(KB_DEVICE_TYPE, 0xF03, METHOD_BUFFERED, FILE_ANY_ACCESS)

// ============================================
// Version Info
// ============================================

#define KB_VERSION_MAJOR    1
#define KB_VERSION_MINOR    0
#define KB_VERSION_PATCH    0
#define KB_VERSION          ((KB_VERSION_MAJOR << 16) | (KB_VERSION_MINOR << 8) | KB_VERSION_PATCH)

